# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b6505eba1900c06343c29713b762f08d44151d284e60e790d6c30812e25c6b9fd47b31fdf946960bf419abdf15d5317679ae1e2301ada4ae6fa7043bb8b58db

test:
  secret_key_base: 8b9b82923e7f0e4a6868c7427e7f0976f9fcb566530994ea56344507c0862ad4de2fd4157abf3818a40348e85a35aad7e1c8333b6f4814523ed5c04077af51bc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
